Commit 26

diff --git a/.github/workflows/simple.yml b/.github/workflows/simple.yml
--- a/.github/workflows/simple.yml
+++ b/.github/workflows/simple.yml
@@ -37,10 +37,9 @@ jobs:
 
           http_code=${CURL_RESPONSE: -3}; echo http status code - $http_code
           content=${CURL_RESPONSE}; echo response - $content
-          if [[ $http_code != "200" ]] || [[ $http_code != "201" ]]
-          then
-          echo "FAILURE"
-          exit 1
+          if [[ $http_code != "200" ] || [ $http_code != "201" ]]; then
+            echo "FAILURE"
+            exit 1
           else
-          echo "SUCCESS"
+            echo "SUCCESS"
           fi
